import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.170.0/build/three.module.js';
import { OrbitControls } from 'https://cdn.jsdelivr.net/npm/three@0.170.0/examples/jsm/controls/OrbitControls.js';

const baseParts = __BASE_PARTS__;
const keyboards = __KEYBOARDS__;
const PRICE_DATE = '__PRICE_DATE__';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const euro=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n);
const fmt=n=>`${Math.round(n*10)/10} mm`;

const canvas=$('#canvas');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene(); scene.fog=new THREE.FogExp2(0x071018,.0022);
const camera=new THREE.PerspectiveCamera(36,1,1,1200);
const controls=new OrbitControls(camera,canvas); controls.enableDamping=true; controls.dampingFactor=.07; controls.minDistance=110; controls.maxDistance=540; controls.target.set(0,10,0);
scene.add(new THREE.HemisphereLight(0xc9ecff,0x16202a,2.4)); const keyLight=new THREE.DirectionalLight(0xffffff,3); keyLight.position.set(120,180,200); keyLight.castShadow=true; scene.add(keyLight); const rim=new THREE.DirectionalLight(0x52d3ff,1.2);rim.position.set(-160,40,-100);scene.add(rim);
const ground=new THREE.Mesh(new THREE.CircleGeometry(360,96),new THREE.MeshStandardMaterial({color:0x081018,roughness:1,metalness:0}));ground.rotation.x=-Math.PI/2;ground.position.y=-92;ground.receiveShadow=true;scene.add(ground);
const grid=new THREE.GridHelper(600,60,0x17384e,0x102330);grid.position.y=-91.5;scene.add(grid);

const root=new THREE.Group(); scene.add(root);
const materials={shell:new THREE.MeshPhysicalMaterial({color:0x18242f,roughness:.5,metalness:.15,clearcoat:.25,transparent:true,opacity:.72}),shellEdge:new THREE.MeshStandardMaterial({color:0x27394a,roughness:.6}),screen:new THREE.MeshPhysicalMaterial({color:0x102d3f,emissive:0x0f8eb5,emissiveIntensity:.22,roughness:.18,metalness:.08,clearcoat:1}),pcb:new THREE.MeshStandardMaterial({color:0x155e46,roughness:.65}),pcb2:new THREE.MeshStandardMaterial({color:0x234b79,roughness:.65}),gold:new THREE.MeshStandardMaterial({color:0xd2a84a,metalness:.65,roughness:.35}),black:new THREE.MeshStandardMaterial({color:0x080a0c,roughness:.48}),metal:new THREE.MeshStandardMaterial({color:0xa8b4bd,metalness:.72,roughness:.3}),battery:new THREE.MeshStandardMaterial({color:0x8a3752,roughness:.55}),batteryCap:new THREE.MeshStandardMaterial({color:0xb8c0c8,metalness:.7,roughness:.25}),switch:new THREE.MeshStandardMaterial({color:0xe3e8ed,roughness:.5}),key:new THREE.MeshStandardMaterial({color:0x10151a,roughness:.62}),accent:new THREE.MeshStandardMaterial({color:0x22c55e,emissive:0x10351d,emissiveIntensity:.3}),antenna:new THREE.MeshStandardMaterial({color:0x111316,roughness:.45}),rj45:new THREE.MeshStandardMaterial({color:0x9aa9b4,metalness:.7,roughness:.25})};

let state={keyboard:'cardkb',mode:'assembly',explode:0,selected:null};
let objects=new Map(); let currentCase={w:116,h:160,d:30};
function clearRoot(){while(root.children.length) root.remove(root.children[0]);objects.clear()}
function box(name,size,pos,mat=materials.pcb,parent=root,round=false){const g=round?new THREE.BoxGeometry(...size,5,5,5):new THREE.BoxGeometry(...size);const m=new THREE.Mesh(g,mat);m.position.set(...pos);m.castShadow=true;m.receiveShadow=true;m.userData.name=name;parent.add(m);return m}
function cyl(name,r,len,pos,rot=[0,0,0],mat=materials.metal,parent=root){const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,len,32),mat);m.position.set(...pos);m.rotation.set(...rot);m.castShadow=true;m.userData.name=name;parent.add(m);return m}
function groupObj(id,label,basePos=[0,0,0]){const g=new THREE.Group();g.userData={id,label,basePos:new THREE.Vector3(...basePos)};g.position.set(...basePos);root.add(g);objects.set(id,g);return g}
function pcbWithPins(g,w,h,d=2){box('pcb',[w,h,d],[0,0,0],materials.pcb,g);for(let y=-h/2+4;y<h/2-2;y+=5){for(const x of [-w/2+2,w/2-2])cyl('pin',.55,2.5,[x,y,d/2+1.2],[Math.PI/2,0,0],materials.gold,g)}}
function addTextPlate(g,text,w=24,h=7,z=4){const c=document.createElement('canvas');c.width=512;c.height=128;const x=c.getContext('2d');x.fillStyle='#0c151d';x.fillRect(0,0,c.width,c.height);x.fillStyle='#c9f4ff';x.font='700 42px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(text,c.width/2,c.height/2);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:t,transparent:true}));m.position.z=z;m.userData.name=text;g.add(m)}
function roundedShellPart(w,h,d,y,z,top=true){const g=new THREE.BoxGeometry(w,h,d,8,8,3);const m=new THREE.Mesh(g,materials.shell);m.position.set(0,y,z);m.castShadow=true;return m}
function caseSizeFor(k){const kw=k.dims[0],kh=k.dims[1],kd=k.dims[2];const w=Math.max(116,kw+14);const upper=86;const h=upper+kh+18;const d=Math.max(30,Math.min(37,kd+17));return {w,h,d,upper}}
function buildShell(k){const s=caseSizeFor(k);currentCase=s;const g=groupObj('shell','Gehäuse',[0,0,0]);const top=roundedShellPart(s.w,s.h,3,0,s.d/2-1.5);const bottom=roundedShellPart(s.w,s.h,3,0,-s.d/2+1.5);g.add(top,bottom);const sideT=3;box('left wall',[sideT,s.h,s.d-6],[-s.w/2+1.5,0,0],materials.shellEdge,g);box('right wall',[sideT,s.h,s.d-6],[s.w/2-1.5,0,0],materials.shellEdge,g);box('top wall',[s.w-6,sideT,s.d-6],[0,s.h/2-1.5,0],materials.shellEdge,g);box('bottom wall',[s.w-6,sideT,s.d-6],[0,-s.h/2+1.5,0],materials.shellEdge,g);
  const displayY=s.h/2-39; const bezel=box('display bezel',[106,66,2],[0,displayY,s.d/2+.8],materials.black,g);bezel.material=materials.black;
  box('keyboard recess',[Math.min(k.dims[0]+4,s.w-8),Math.min(k.dims[1]+4,s.h-90),2],[0,-s.h/2+k.dims[1]/2+8,s.d/2+.9],materials.black,g);
}
function buildDisplay(){const y=currentCase.h/2-39;const g=groupObj('display','3.5″ TFT',[0,y,currentCase.d/2+3.8]);box('display pcb',[98,56.3,2],[0,0,0],materials.pcb2,g);box('LCD',[84,50,3],[0,0,2.3],materials.screen,g);addTextPlate(g,'3.5″ TFT',30,7,4.1);box('microSD slot',[18,8,3],[36,-24,1.8],materials.metal,g)}
function buildS3(){const g=groupObj('s3','ESP32-S3',[currentCase.w*.22,currentCase.h*.09,1]);pcbWithPins(g,25.4,63,2);box('S3 WROOM',[18,25,3],[0,8,2.4],materials.metal,g);box('USB-C',[9,7,4],[0,-28,2.5],materials.metal,g);addTextPlate(g,'S3',15,6,4)}
function buildC5(){const g=groupObj('c5','ESP32-C5',[currentCase.w*.26,-4,4]);box('C5 module',[18,27.5,3.3],[0,0,0],materials.metal,g);addTextPlate(g,'C5',12,5,1.9);cyl('U.FL',1.5,2,[7,10,2],[Math.PI/2,0,0],materials.gold,g)}
function buildW5500(){const g=groupObj('w5500','W5500 Ethernet',[-currentCase.w*.25,currentCase.h*.04,0]);box('W5500 pcb',[28,55,2],[0,0,0],materials.pcb,g);box('RJ45',[23,20,16],[0,17,8],materials.rj45,g);box('W5500 IC',[10,10,2],[0,-10,2],materials.black,g);addTextPlate(g,'W5500',18,5,4)}
function buildBatteryShield(){const g=groupObj('batteryShield','Dual 18650 Shield',[0,-currentCase.h*.12,-5]);box('power pcb',[42,98,2],[0,0,0],materials.pcb2,g);box('boost',[15,12,3],[0,40,2],materials.black,g);box('USB-C power',[10,7,4],[0,-45,2],materials.metal,g)}
function buildBatteries(){for(const [id,x] of [['batteryA',-12],['batteryB',12]]){const g=groupObj(id,id==='batteryA'?'18650 A':'18650 B',[x,-currentCase.h*.12,5]);cyl('18650',9.25,65.3,[0,0,0],[0,0,0],materials.battery,g);cyl('cap',8.7,1.5,[0,33,0],[0,0,0],materials.batteryCap,g);cyl('cap',8.7,1.5,[0,-33,0],[0,0,0],materials.batteryCap,g)}}
function buildUSB(){const g=groupObj('usbC','USB-C Breakout',[currentCase.w/2-18,-currentCase.h/2+14,0]);box('USB board',[18,24,2],[0,0,0],materials.pcb,g);box('USB-C',[10,8,5],[0,-9,2.5],materials.metal,g)}
function buildAntennas(){const a=groupObj('wifiAnt','WLAN Antenne',[currentCase.w/2+8,currentCase.h/2-25,0]);cyl('antenna',4.5,70,[0,0,0],[0,0,0],materials.antenna,a);const b=groupObj('btAnt','BT/FPC Antenne',[-currentCase.w/2+10,currentCase.h/2-28,-3]);box('FPC',[14,42,1],[0,0,0],materials.gold,b)}
function buildNav(){const g=groupObj('nav','5× Kailh Choc Navigation',[0,currentCase.h/2-80,currentCase.d/2+6]);const pts=[[0,12],[-12,0],[0,0],[12,0],[0,-12]];for(const [x,y] of pts){box('choc',[10,10,5],[x,y,0],materials.switch,g);box('cap',[11.5,11.5,3],[x,y,4],materials.key,g)}}
function buildMicroSD(){const g=groupObj('microsd','microSD 32GB',[currentCase.w*.1,currentCase.h*.02,5]);box('microSD',[11,15,1],[0,0,0],materials.black,g)}
function buildKeyboard(k){const y=-currentCase.h/2+k.dims[1]/2+8;const g=groupObj('keyboard',k.name,[0,y,currentCase.d/2+k.dims[2]/2+1]);const w=k.dims[0],h=k.dims[1],d=k.dims[2];
  box('keyboard body',[w,h,Math.max(2,d)],[0,0,0],materials.black,g);
  const isBB=k.group==='BlackBerry', isCard=k.id==='cardkb'||k.id==='keebdeck';
  if(isBB){const rows=4,cols=10;const keyW=Math.min(6.2,w/(cols+1)),keyH=Math.min(7.2,h/(rows+2));for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const x=(c-(cols-1)/2)*keyW*1.02;const yy=(r-(rows-1)/2)*keyH-3;box('bb key',[keyW*.9,keyH*.82,1.5],[x,yy,d/2+.8],materials.key,g)}box('trackpad',[12,9,1.5],[0,h/2-9,d/2+.8],materials.screen,g)}
  else if(isCard){const rows=5,cols=10;const keyW=(w-8)/cols,keyH=(h-8)/rows;for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){box('card key',[keyW*.78,keyH*.7,1.6],[-w/2+5+keyW*(c+.5),-h/2+5+keyH*(r+.5),d/2+.8],materials.key,g)}}
  else {const rows=5,cols=10;const usableW=w*.62,keyW=usableW/cols,keyH=Math.min(11,(h-14)/rows);for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){box('rii key',[keyW*.78,keyH*.7,1.5],[-w/2+8+keyW*(c+.5),-h/2+8+keyH*(r+.5),d/2+.8],materials.key,g)}box('touchpad',[w*.28,h*.5,1.4],[w*.32,0,d/2+.8],materials.screen,g)}
  addTextPlate(g,k.name.replace('Rii Mini ','Rii '),Math.min(45,w*.45),6,d/2+2.1);
}
function buildAll(){clearRoot();const k=keyboards.find(x=>x.id===state.keyboard);buildShell(k);buildDisplay();buildS3();buildC5();buildW5500();buildBatteryShield();buildBatteries();buildUSB();buildAntennas();buildNav();buildMicroSD();buildKeyboard(k);applyMode();updateUI()}
const explosionVectors={shell:[0,0,0],display:[0,1,.8],s3:[1,.15,.55],c5:[1,-.2,.35],w5500:[-1,.2,.2],batteryShield:[0,-.35,-.7],batteryA:[-.55,-.2,.55],batteryB:[.55,-.2,.55],usbC:[1,-.8,.1],wifiAnt:[1,.8,.2],btAnt:[-1,.75,-.1],nav:[0,.4,1],microsd:[.2,.2,.7],keyboard:[0,-1,.8]};
function applyMode(){const amount=state.mode==='exploded'?Math.max(state.explode,.18):state.mode==='assembly'?state.explode:0;for(const [id,g] of objects){const base=g.userData.basePos||new THREE.Vector3();const v=explosionVectors[id]||[0,0,0];const scale=amount*75;g.position.copy(base).add(new THREE.Vector3(v[0]*scale,v[1]*scale,v[2]*scale));g.visible=!state.selected||id===state.selected||(state.selected==='batteryA'&&id==='batteryB');}
  $('#modeChip').textContent=(state.selected?'COMPONENT · ':state.mode.toUpperCase());
}
function setSelected(id){state.selected=id;state.mode='component';$$('.compBtn').forEach(b=>b.classList.toggle('active',b.dataset.id===id));applyMode();const g=objects.get(id);if(g){const p=g.position.clone();controls.target.copy(p);camera.position.copy(p.clone().add(new THREE.Vector3(95,72,130)));}updateUI()}
function resetSelection(){state.selected=null;state.mode='assembly';$$('.compBtn').forEach(b=>b.classList.remove('active'));$$('.seg button').forEach(b=>b.classList.toggle('active',b.dataset.view==='assembly'));applyMode();resetCamera()}
function resetCamera(){const s=currentCase;controls.target.set(0,0,0);const dist=Math.max(s.w,s.h)*1.45;camera.position.set(dist*.72,dist*.55,dist);controls.update()}
function partPrice(){return baseParts.reduce((a,p)=>a+p.price*p.qty,0)}
function updateUI(){const k=keyboards.find(x=>x.id===state.keyboard),s=currentCase;$('#kbdDims').textContent=`${k.dims[0]}×${k.dims[1]}×${k.dims[2]} mm`;$('#kbdTitle').textContent=k.name;$('#kbdMeta').innerHTML=`${k.interface}<br>${k.note}`;$('#kbdRecommend').textContent=k.id==='bbq20'?'Sehr starker Handheld-Kandidat: klein + Trackpad + BLE/USB.':k.id==='cardkb'?'Sehr kompakt und direkt per I²C am S3 nutzbar.':k.id==='keebdeck'?'Extrem kompakt; perfekt, wenn du später eine eigene Haupt-PCB machst.':k.group==='Rii'?'Rii macht das Gerät deutlich breiter; X1/i10 sind die flachsten Varianten.':'Alternative Eingabeoption.';$('#kbdChip').textContent=k.name;$('#dimW').textContent=fmt(s.w);$('#dimH').textContent=fmt(s.h);$('#dimD').textContent=fmt(s.d);$('#explodeValue').textContent=`${Math.round(state.explode*100)}%`;const total=partPrice()+k.price;$('#totalPrice').textContent=euro(total);$('#headerPrice').textContent=euro(total);$('#priceDate').textContent=`Stand ${PRICE_DATE}`;
  $('#keyboardPrice').innerHTML=`<div class="priceRow"><div><a href="${k.source}" target="_blank" rel="noreferrer">${k.name}</a><span class="sub">${k.interface} · ${k.dims.join(' × ')} mm ${k.priceType==='estimate'?'<span class="tag warning">Schätzung</span>':''}</span></div><strong>${euro(k.price)}</strong></div>`;
}
function buildLists(){const sel=$('#keyboardSelect');const groups=[...new Set(keyboards.map(k=>k.group))];sel.innerHTML=groups.map(g=>`<optgroup label="${g}">${keyboards.filter(k=>k.group===g).map(k=>`<option value="${k.id}">${k.name} — ${euro(k.price)}</option>`).join('')}</optgroup>`).join('');sel.value=state.keyboard;
  const ids=['shell','display','s3','c5','w5500','batteryShield','batteryA','usbC','wifiAnt','btAnt','nav','microsd','keyboard'];$('#componentList').innerHTML=ids.map(id=>`<button class="compBtn" data-id="${id}"><span>${id==='keyboard'?'Gewählte Tastatur':(baseParts.find(p=>p.id===id)?.name||id)}</span><small>3D</small></button>`).join('');
  $('#partsTable').innerHTML=baseParts.map(p=>`<div class="priceRow"><div>${p.source.startsWith('http')?`<a href="${p.source}" target="_blank" rel="noreferrer">${p.name}</a>`:p.name}<span class="sub">${p.qty>1?`${p.qty} × ${euro(p.price)} · `:''}${p.priceType==='estimate'?'<span class="tag warning">Schätzung</span>':''}</span></div><strong>${euro(p.price*p.qty)}</strong></div>`).join('');
  $$('.compBtn').forEach(b=>b.addEventListener('click',()=>setSelected(b.dataset.id)));
}
$('#keyboardSelect').addEventListener('change',e=>{state.keyboard=e.target.value;state.selected=null;buildAll();resetCamera()});$('#explode').addEventListener('input',e=>{state.explode=Number(e.target.value)/100;if(state.mode==='assembly'&&state.explode>.02){state.mode='exploded';$$('.seg button').forEach(b=>b.classList.toggle('active',b.dataset.view==='exploded'))}applyMode();updateUI()});$$('.seg button').forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.view;$$('.seg button').forEach(x=>x.classList.toggle('active',x===b));if(v==='component'){if(!state.selected)setSelected('s3')}else{state.selected=null;state.mode=v;applyMode();resetCamera()}updateUI()}));$('#resetCamera').addEventListener('click',()=>{state.selected=null;applyMode();resetCamera()});
$('#openParts').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$('#openInfo').addEventListener('click',()=>$('#inspector').classList.toggle('open'));canvas.addEventListener('pointerdown',()=>{$('#sidebar').classList.remove('open');$('#inspector').classList.remove('open')});
function resize(){const r=canvas.parentElement.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(canvas.parentElement);
function tick(){requestAnimationFrame(tick);controls.update();renderer.render(scene,camera)}
buildLists();buildAll();resetCamera();resize();tick();
