export const PRICE_DATE = '16.08.2026';

export const baseParts = [
  {id:'shell', name:'3D-gedrucktes Gehäuse', qty:1, price:8.00, priceType:'estimate', dimsType:'estimate', dims:[116,182,36], source:'Schätzung für PLA/PETG; abhängig von Druckservice und Material'},
  {id:'display', name:'3.5″ SPI TFT ILI9488', qty:1, price:22.95, dimsType:'depth-unverified', dims:[98,56.3,6], source:'https://www.fruugo.de/35-zoll-spi-lcd-modul-mit-serieller-schnittstelle-und-tft-display-ili9488-multifunktions-tragbar-mit-kapazitivem-tou/p-360270940-783374477'},
  {id:'s3', name:'ESP32-S3-DevKitC-1U-N8R8', qty:1, price:12.90, dims:[25.4,62.74,11], source:'https://www.mouser.de/ProductDetail/Espressif-Systems/ESP32-S3-DevKitC-1U-N8R8'},
  {id:'c5', name:'ESP32-C5-WROOM-1U-N8R8', qty:1, price:4.84, dims:[18,21.2,3.3], source:'https://eu.mouser.com/en/ProductDetail/Espressif-Systems/ESP32-C5-WROOM-1U-N8R8', specSource:'https://documentation.espressif.com/esp32-c5-wroom-1_wroom-1u_datasheet_en.html', integrationNote:'SMD-Modul; Carrier, Versorgung, Reset und Programmierung sind nicht Teil der BOM.'},
  {id:'w5500', name:'W5500 SPI Ethernet Modul', qty:1, price:9.70, dims:[23,29,24], source:'https://www.berrybase.de/w5500-spi-ethernet-modul'},
  {id:'batteryShield', name:'Dual 18650 Battery Shield V8', qty:1, price:7.44, dimsType:'estimate', dims:[49,101,21], source:'https://www.ebay.de/itm/202607996211'},
  {id:'batteryA', name:'Samsung INR18650-35E', qty:2, price:3.99, dims:[18.5,65.3,18.5], source:'https://geizhals.de/samsung-sdi-18650-li-ion-3500mah-inr18650-35e-a1513665.html'},
  {id:'microsd', name:'SanDisk Ultra microSDHC 32GB', qty:1, price:15.99, dims:[11,15,1], source:'https://www.mediamarkt.de/de/product/_sandisk-186500-2698324.html'},
  {id:'usbC', name:'USB-C Breakout Board', qty:1, price:1.85, dimsType:'height-unverified', dims:[22,22,5], source:'https://www.berrybase.de/soldered-usb-c-buchse-breakout-board-tht-pins', specSource:'https://soldered.com/products/usb-c-female-connector-breakout', integrationNote:'Nur Stecker-Breakout; kein USB-Host, PD-Controller oder Ladegerät.'},
  {id:'nav', name:'Kailh Choc V1 Switches (10er-Pack, 5 genutzt)', qty:1, price:5.90, dimsType:'layout-estimate', dims:[35.5,35.5,12], source:'https://www.keebart.com/de/produkte/choc-switches'},
  {id:'caps', name:'MBK Choc Keycaps (10er-Pack)', qty:1, price:4.50, dimsType:'layout-estimate', dims:[55,55,5], source:'https://www.keebart.com/de/produkte/mbk-blanks'},
  {id:'wifiAnt', name:'2.4/5.8 GHz Antenne + U.FL/SMA', qty:1, price:9.87, dims:[9.5,85,9.5], source:'https://www.henri.de/buero-pc-nb/w-lan/wlan-antennen/34518/wlan-antenne-2-4-5-8ghz-mit-sma-rev-stecker-und-pigtail-ufl-ipx-adapter-auch-fuer-bluetooth-geeignet.html', integrationNote:'Lieferumfang des U.FL-zu-RP-SMA-Pigtails vor Bestellung bestätigen.'},
  {id:'btAnt', name:'Interne Dual-Band FPC-Antenne U.FL', qty:1, price:2.80, dims:[13,95,1], source:'https://www.berrybase.de/dual-band-wlan-antenne-2.4ghz-5.8ghz-u.fl-anschluss'},
  {id:'breadboard', name:'Mini Breadboard (170 Kontakte)', qty:1, price:3.50, priceType:'estimate', dims:[47,35,8.5], source:'Schätzung; exakte Ausführung vor Gehäusebau auswählen'},
  {id:'misc', name:'Kabel, Header, Schrauben, Inserts', qty:1, price:5.00, priceType:'estimate', dims:[20,20,8], source:'Schätzung'}
];

export const keyboards = [
  {id:'cardkb', name:'M5Stack CardKB v1.1', group:'Card', dims:[88,54,5], price:8.80, interface:'I²C', note:'Sehr kompakt; 50 Tasten.', source:'https://eu.robotshop.com/products/m5stack-cardkb-mini-keyboard-programmable-unit-v11-mega8a', specSource:'https://shop.m5stack.com/products/cardkb-mini-keyboard-programmable-unit-v1-1-mega8a'},
  {id:'keebdeck', name:'Solder Party KeebDeck Keyboard', group:'Card', dims:[85.8,48.6,4], price:3.80, interface:'Matrix / eigene PCB', note:'69 Tasten, extrem kompakt; benötigt PCB/Dome-Sheet-Integration.', source:'https://lectronz.com/products/keebdeck-keyboard', specSource:'https://www.solder.party/docs/keebdeck/keyboard/dimensions-v1.pdf'},
  {id:'rii-x1', name:'Rii Mini X1', group:'Rii', dims:[152,59,12.5], price:18.99, interface:'2.4 GHz USB-Dongle', note:'Flachste Rii-Option, aber USB-Host/Dongle nötig.', source:'https://www.riimall.com/collections/mini-keyboard'},
  {id:'rii-i10', name:'Rii Mini i10 Wireless', group:'Rii', dims:[153,63,12], price:24.99, interface:'2.4 GHz USB-Dongle', note:'Sehr flach und schmal; 70 Tasten.', source:'https://www.riitek.eu/DE/Produkte/RT-MWK10RF_DE.html'},
  {id:'rii-i4', name:'Rii Mini i4', group:'Rii', dims:[155,89,16.5], price:38.00, interface:'Bluetooth 4.0 + 2.4 GHz', note:'Bluetooth ist praktisch, aber deutlich breiter/höher.', source:'https://www.riimall.com/collections/mini-keyboard'},
  {id:'rii-i8', name:'Rii Mini i8', group:'Rii', dims:[138,96,23], price:19.99, interface:'2.4 GHz USB-Dongle', note:'Kompakt, aber recht dick.', source:'https://www.riitek.eu/DE/Produkte/RT-MWK08RF_DE.html'},
  {id:'rii-i8plus', name:'Rii Mini i8+', group:'Rii', dims:[146,97.5,19.8], price:23.99, interface:'2.4 GHz USB-Dongle', note:'Beleuchtet; größer als i10/X1.', source:'https://www.riimall.com/collections/mini-keyboard'},
  {id:'rii-x8', name:'Rii Mini X8', group:'Rii', dims:[138,96,21], dimsType:'revision-conflict', price:21.84, interface:'2.4 GHz USB-Dongle', note:'Touchpad + Scrollrad; Herstellerquellen widersprechen sich bei den Abmessungen, Revision vor Gehäusebau prüfen.', source:'https://www.riitek.eu/IT/Prodotti/X8_IT.html'},
  {id:'rii-x8plus', name:'Rii Mini X8+', group:'Rii', dims:[138,96,23], price:24.99, interface:'2.4 GHz USB-Dongle', note:'X8+-Formfaktor; Preis als Näherung aus Rii-Mini-Marktbereich.', source:'https://www.riimall.com/collections/mini-keyboard', priceType:'estimate'},
  {id:'rii-i8x', name:'Rii Mini i8X', group:'Rii', dims:[138,96,23], price:24.99, interface:'2.4 GHz USB-Dongle', note:'Neuere i8-Variante; Preis und Verfügbarkeit unbestätigt.', source:'https://www.riimall.com/collections/mini-keyboard', priceType:'estimate'},
  {id:'rii-i8s', name:'Rii Mini i8S', group:'Rii', dims:[138,96,23], price:24.99, interface:'2.4 GHz USB-Dongle', note:'i8-Familie; Preis und Verfügbarkeit unbestätigt.', source:'https://www.riimall.com/collections/mini-keyboard', priceType:'estimate'},
  {id:'rii-k06', name:'Rii Mini K06', group:'Rii', dims:[155,89,16.5], price:29.99, interface:'Bluetooth + 2.4 GHz', note:'Dual-Mode mit Touchpad; Herstellermaß 155 × 89 × 16,5 mm. Preis als Markt-Richtwert.', source:'https://www.riimall.com/collections/mini-keyboard', priceType:'estimate'},
  {id:'rii-518bt', name:'Rii 518BT Mini Bluetooth', group:'Rii', dims:[108.5,58.2,10.2], dimsType:'primary-unconfirmed', price:39.52, interface:'Bluetooth 3.0', note:'Sehr kompakte Rii-Bluetooth-Option; Abmessungen vor Gehäusebau bestätigen.', source:'https://www.ebay.de/itm/397821260875', specSource:'https://www.riimall.com/products/rii-518bt-mini-keyboard'},
  {id:'rii-v3', name:'Rii Mini V3', group:'Rii', dims:[152,59,12.5], price:21.99, interface:'2.4 GHz USB-Dongle', note:'Flacher X1-ähnlicher Formfaktor; Preis als Näherung anhand aktueller K01V3-Angebote.', source:'https://www.riimall.com/collections/mini-keyboard', priceType:'estimate'},
  {id:'rii-rk707', name:'Rii RK707 Gamepad Keyboard', group:'Rii', dims:[141.3,92.5,27.5], price:36.99, interface:'2.4 GHz USB-Dongle', note:'Keyboard + Touchpad + Gamepad; deutlich dicker.', source:'https://www.riimall.com/collections/mini-keyboard'},
  {id:'rii-i12plus', name:'Rii Mini i12+', group:'Rii', dims:[262,85,14], price:27.99, interface:'2.4 GHz USB-Dongle', note:'Offiziell Mini-Serie, aber für ein Handheld mit 262 mm sehr breit; Preis als Markt-Näherung.', source:'https://www.riimall.com/collections/mini-keyboard', priceType:'estimate'},
  {id:'bbq20', name:'BlackBerry Q20 / BBQ20 BLE+USB', group:'BlackBerry', dims:[81.95,54.97,13.3], price:43.04, interface:'BLE 5 + USB', availability:'coming-soon', note:'Winzig, Trackpad, sehr guter Handheld-Formfaktor; derzeit als „coming soon“ gelistet.', source:'https://lectronz.com/products/blackberry-bbq20-bleusb-keyboard'},
  {id:'bbq10', name:'BlackBerry Q10 / BBQ10 BLE+USB', group:'BlackBerry', dims:[76.67,53.13,12.9], price:38.41, interface:'BLE 5 + USB', availability:'sold-out', note:'Noch etwas kleiner; derzeit ausverkauft.', source:'https://lectronz.com/products/blackberry-q10-bleusb-keyboard'},
  {id:'bb9900', name:'BlackBerry 9900 BLE+USB', group:'BlackBerry', dims:[74.57,56.91,13.1], price:41.15, interface:'BLE 5 + USB', availability:'sold-out', note:'Smile-Layout + Trackpad; derzeit ausverkauft.', source:'https://lectronz.com/products/blackberry-bb9900-bleusb-keyboard'}
];
